# Utilisez l'image de base de votre choix
FROM node:latest

# Définissez le répertoire de travail dans le conteneur
WORKDIR /app

# Copiez les fichiers du projet dans le conteneur
COPY . .

# Installez les dépendances avec yarn
RUN yarn install

# Construisez l'application frontend
RUN yarn build

# Exposez le port utilisé par l'application
EXPOSE 3000

# Commande pour démarrer le serveur de développement
CMD ["yarn", "start"]
