services:
  db:
    image: mysql:latest
    container_name: bd_photo
    environment:
      MYSQL_ROOT_PASSWORD: 2204
      MYSQL_DATABASE: dbphoto
    networks:
      - reseau_photo
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: ./backend
    container_name: backend_photo
    ports:
      - "5000:5000"
    networks:
      - reseau_photo
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    container_name: frontend_photo
    ports:
      - "3000:3000"
    networks:
      - reseau_photo
    depends_on:
      - backend

networks:
  reseau_photo:
    driver: bridge
