# Utiliser l'image de base node
FROM node:latest

# Définir le répertoire de travail dans le conteneur
WORKDIR /app

# Ajuster les permissions
RUN chmod -R 755 /app

# Copier package.json et yarn.lock pour installer les dépendances
COPY package.json yarn.lock ./

# Installer les dépendances
RUN yarn install

# Installer TypeScript globalement
RUN yarn global add typescript

# Copier les fichiers du projet dans le conteneur
COPY . .

# installation des déclarations de types pour multer et jsonwebtoken
RUN yarn add @types/multer @types/jsonwebtoken --dev

# YARN
RUN yarn

# mise a jour des paquets de types
RUN yarn upgrade @types/express @types/multer

# Exposer le port utilisé par l'application
EXPOSE 5000

# Commande pour démarrer l'application
CMD ["yarn", "start"]
